const PROGRAMA_INGENIERIA = 'Ingenieria de Telecomunicaciones';
const PROGRAMA_TECNOLOGIA = 'Tecnologia en Gestion de Sistemas de Telecomunicaciones';

const materiasIngenieria = [
    { codigo: 'DDI012', nombre: 'INGLES III', semestre: 1 },
    { codigo: 'PTC102', nombre: 'LINUX', semestre: 1 },
    { codigo: 'DCB020', nombre: 'ALGEBRA LINEAL', semestre: 1 },
    { codigo: 'DCB007', nombre: 'ECUACIONES DIFERENCIALES', semestre: 1 },
    { codigo: 'DCB030', nombre: 'ESTADISTICA PARA INGENIEROS', semestre: 1 },
    { codigo: 'DCB023', nombre: 'ONDAS Y PARTICULAS', semestre: 1 },
    { codigo: 'PTC101', nombre: 'BASES DE DATOS', semestre: 2 },
    { codigo: 'PTC402', nombre: 'ADMINISTRACION DE REDES', semestre: 2 },
    { codigo: 'DDI013', nombre: 'INGLES IV', semestre: 2 },
    { codigo: 'PTC205', nombre: 'SENALES Y SISTEMAS', semestre: 2 },
    { codigo: 'PTC204', nombre: 'SERVICIOS BAJO LINUX', semestre: 2 },
    { codigo: 'DCB032', nombre: 'ANALISIS NUMERICO', semestre: 2 },
    { codigo: 'PTC301', nombre: 'COMUNICACIONES INALAMBRICAS', semestre: 3 },
    { codigo: 'PTC00E', nombre: 'ELECTIVA DE PROFUNDIZACION III', semestre: 3 },
    { codigo: 'DHI030', nombre: 'EMPRENDIMIENTO', semestre: 3 },
    { codigo: 'DHI024', nombre: 'METODOLOGIA DE LA INVESTIGACION II', semestre: 3 },
    { codigo: 'DHO00C', nombre: 'OPTATIVA III', semestre: 3 },
    { codigo: 'PTC306', nombre: 'PROGRAMACION EN JAVA', semestre: 3 },
    { codigo: 'PTC307', nombre: 'TELEFONIA IP', semestre: 3 },
    { codigo: 'PTC302', nombre: 'LABORATORIO DE COMUNICACIONES INALAMBRICAS', semestre: 4 },
    { codigo: 'PTC303', nombre: 'REDES DE BANDA ANCHA', semestre: 4 },
    { codigo: 'PTC406', nombre: 'COMUNICACIONES AVANZADAS', semestre: 4 },
    { codigo: 'PTC00F', nombre: 'ELECTIVA DE PROFUNDIZACION IV', semestre: 4 },
    { codigo: 'DHO00D', nombre: 'OPTATIVA IV', semestre: 4 },
    { codigo: 'PTC405', nombre: 'PROGRAMACION DE DISPOSITIVOS MOVILES', semestre: 4 },
    { codigo: 'PTC404', nombre: 'SEGURIDAD EN REDES', semestre: 4 },
];

const materiasTecnologia = [
    { codigo: 'DCB001', nombre: 'ALGEBRA SUPERIOR', semestre: 1 },
    { codigo: 'DCB002', nombre: 'CALCULO DIFERENCIAL', semestre: 1 },
    { codigo: 'FCN006', nombre: 'LOGICA Y ALGORITMOS', semestre: 1 },
    { codigo: 'TTC101', nombre: 'MEDIOS DE TRANSMISION', semestre: 1 },
    { codigo: 'DHI014', nombre: 'PROCESOS DE LECTURA Y ESCRITURA', semestre: 1 },
    { codigo: 'DHI016', nombre: 'CULTURA FISICA', semestre: 1 },
    { codigo: 'FCN001', nombre: 'ANALISIS DE CIRCUITOS ELECTRICOS I', semestre: 2 },
    { codigo: 'FCN015', nombre: 'LABORATORIO MEDIDAS Y CIRCUITOS ELECTRICOS', semestre: 2 },
    { codigo: 'DCB009', nombre: 'MECANICA', semestre: 2 },
    { codigo: 'DHO00A', nombre: 'OPTATIVA I', semestre: 2 },
    { codigo: 'FCN017', nombre: 'PROGRAMACION', semestre: 2 },
    { codigo: 'TTC400', nombre: 'TELEMATICA I', semestre: 2 },
    { codigo: 'DCB003', nombre: 'CALCULO INTEGRAL', semestre: 2 },
    { codigo: 'FCN002', nombre: 'ANALISIS DE CIRCUITOS ELECTRICOS II', semestre: 3 },
    { codigo: 'FCN003', nombre: 'ELECTRONICA I', semestre: 3 },
    { codigo: 'DCB010', nombre: 'ELECTROMAGNETISMO', semestre: 3 },
    { codigo: 'DHI029', nombre: 'EPISTEMOLOGIA', semestre: 3 },
    { codigo: 'DHO00B', nombre: 'OPTATIVA II', semestre: 3 },
    { codigo: 'TTC501', nombre: 'TELEMATICA II', semestre: 3 },
    { codigo: 'FCN004', nombre: 'ELECTRONICA II', semestre: 4 },
    { codigo: 'DDI009', nombre: 'INGLES I', semestre: 4 },
    { codigo: 'FCN007', nombre: 'COMUNICACIONES ANALOGAS', semestre: 4 },
    { codigo: 'FCN010', nombre: 'LABORATORIO COMUNICACIONES ANALOGAS', semestre: 4 },
    { codigo: 'TTC402', nombre: 'LABORATORIO DE ELECTRONICA', semestre: 4 },
    { codigo: 'DCB011', nombre: 'LABORATORIO DE FISICA', semestre: 4 },
    { codigo: 'TTC604', nombre: 'TELEMATICA III', semestre: 4 },
    { codigo: 'FCN008', nombre: 'ELECTRONICA DIGITAL', semestre: 5 },
    { codigo: 'FCN009', nombre: 'LABORATORIO DE ELECTRONICA DIGITAL', semestre: 5 },
    { codigo: 'TTC502', nombre: 'COMUNICACIONES DIGITALES I', semestre: 5 },
    { codigo: 'TTC00J', nombre: 'ELECTIVA DE PROFUNDIZACION I', semestre: 5 },
    { codigo: 'DDI010', nombre: 'INGLES II', semestre: 5 },
    { codigo: 'DHI023', nombre: 'METODOLOGIA DE LA INVESTIGACION I', semestre: 5 },
    { codigo: 'TTC503', nombre: 'PROGRAMACION WEB', semestre: 5 },
    { codigo: 'FCN030', nombre: 'INTRODUCCION A LA INGENIERIA', semestre: 6 },
    { codigo: 'TTC600', nombre: 'COMUNICACIONES DIGITALES II', semestre: 6 },
    { codigo: 'TTC607', nombre: 'CONMUTACION DIGITAL', semestre: 6 },
    { codigo: 'TTC00K', nombre: 'ELECTIVA DE PROFUNDIZACION II', semestre: 6 },
    { codigo: 'TTC606', nombre: 'LABORATORIO DE COMUNICACIONES DIGITALES', semestre: 6 },
    { codigo: 'DCB008', nombre: 'CALCULO MULTIVARIABLE', semestre: 6 },
    { codigo: 'DHI003', nombre: 'ETICA', semestre: 6 },
];

export const catalogoMaterias = [
    ...materiasIngenieria.map((materia) => ({ ...materia, programa: PROGRAMA_INGENIERIA })),
    ...materiasTecnologia.map((materia) => ({ ...materia, programa: PROGRAMA_TECNOLOGIA })),
];
